// Copyright (c) Microsoft Corporation.
// Licensed under the Apache 2.0.

/** Filename of the GitHub Actions deployment workflow generated by the agent. */
export const PIPELINE_WORKFLOW_FILENAME = 'deploy-to-aks.yml';

/** Path to the Copilot setup-steps workflow pushed by the setup PR. */
export const COPILOT_SETUP_STEPS_PATH = '.github/workflows/copilot-setup-steps.yml';

/** Path to the containerization agent config pushed by the setup PR. */
export const AGENT_CONFIG_PATH = '.github/agents/containerization.agent.md';

/**
 * GitHub bot usernames that may author PRs created by the Copilot Coding Agent.
 * Stored lowercase — always compare with `.toLowerCase()`.
 */
export const COPILOT_BOT_USERS = new Set(['copilot-swe-agent[bot]', 'copilot[bot]', 'copilot']);

/** Default image tag mandated in agent instructions. */
export const DEFAULT_IMAGE_TAG = '1.0';

/** Custom DOM event used to open the pipeline drawer from a separate React tree. */
export const OPEN_CONFIGURE_PIPELINE_EVENT = 'open-configure-pipeline';
